# Generated by Django 5.1.3 on 2024-12-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_rename_notes_session_description_session_trainer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='category',
            field=models.CharField(choices=[('yoga', 'Yoga'), ('crossfit', 'Crossfit'), ('cardio', 'Cardio'), ('strength', 'Strength Training'), ('pilates', 'Pilates'), ('zumba', 'Zumba'), ('spinning', 'Spinning')], default='yoga', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
